"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
"
"	Table of content
"	0. Plugins
"	1. General
"	2. Colors, fonts and looks
"	3. Tabs / Windows / Buffers
"	4. Text formating
"	5. Editing mappings
"	6. Status and tab line
"
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"	0. Plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" plug.vim
" https://github.com/junegunn/vim-plug

call plug#begin(stdpath('data') . '/plugged')

" Theme
Plug 'iCyMind/NeoSolarized'
Plug 'dracula/vim', { 'as': 'dracula' }

" Basic
Plug 'itchyny/lightline.vim'
Plug 'preservim/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'fladson/vim-kitty'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-session'

" Git
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

" requires 
" https://github.com/sharkdp/bat
" https://github.com/BurntSushi/ripgrep
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Autocompletion
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

"""""""""""""""""""""""""""""""""
"	0.1 NERDTree
"""""""""""""""""""""""""""""""""

" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

" Find current file in tree
nnoremap <leader>ff :NERDTreeFind %<CR>

" reopen NERDTree
nmap FF :NERDTree <CR>

" NERDTree ui
let g:NERDTreeMinimalUI = 1

" Open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" NERDTree on the left
let g:NERDTreeWinPos = "left"

" Open and close node with l and h"
let g:NERDTreeMapActivateNode = "l"
let g:NERDTreeMapOpenRecursively = "L"
let g:NERDTreeMapCloseDir = "h"
let g:NERDTreeMapCloseChildren = "H"

let g:NERDTreeMapToggleHidden = "."

"""""""""""""""""""""""""""""""""
"	0.2 CoC
"""""""""""""""""""""""""""""""""
" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by

" Coc.nvim plugins
" CocInstall coc-tsserver coc-json coc-pairs coc-highlight coc-html coc-css coc-spell-checker

let g:coc_disable_startup_warning = 1

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

" Use `[d` and `]d` to navigate diagnostics
nmap <silent> [d <Plug>(coc-diagnostic-prev)
nmap <silent> ]d <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rr <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f <Plug>(coc-format-selected)

nmap <leader>ff <Plug>(coc-format)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current line.
nmap <leader>a  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Use CTRL-S for selections ranges.
" Requires 'textDocument/selectionRange' support of LS, ex: coc-tsserver
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Mappings using CoCList:
" Show all diagnostics.
nnoremap <silent> <leader>d  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent> <leader>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent> <leader>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent> <leader>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent> <leader>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent> <leader>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent> <leader>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent> <leader>p  :<C-u>CocListResume<CR>

"""""""""""""""""""""""""""""""""
"	0.3 vim-session
"""""""""""""""""""""""""""""""""

" Don't save hidden and unloaded buffers in sessions.
set sessionoptions-=buffers

" Don't persist options and mappings because it can corrupt sessions.
set sessionoptions-=options

" Autosave
let g:session_autosave_periodic=5
let g:session_autosave_silent=0
let g:session_autosave=0

"""""""""""""""""""""""""""""""""
"	0.4 FZF
"""""""""""""""""""""""""""""""""

" Search in code
nnoremap <leader>fd :Rg<CR>

" Search file
nnoremap <leader>fi :Files<CR>

" Search buffer
nnoremap <leader>fb :Buffers<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"	1. General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Map space to leader
let maplocalleader = " "
let mapleader = " "

filetype on
set mouse=a number relativenumber hidden signcolumn=auto ignorecase history=500 updatetime=300 autoread clipboard+=unnamedplus nobackup nowb history=500 so=7 wildmenu cmdheight=1 hid smartcase hlsearch incsearch lazyredraw magic showmatch mat=2 noerrorbells novisualbell tm=500 foldcolumn=1 shortmess+=c t_vb= backspace=eol,start,indent switchbuf=useopen,usetab,newtab whichwrap+=<,>,h,l

" Fast saving
nmap <leader>s :w!<cr>

" Close 
nnoremap <leader>q :q<cr>

" Return to last edit position when opening files (You want this!)
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Disable highlight when <leader><cr> is pressed
map <silent> <leader><ESC> :noh<cr>

" edit and load .vimrc
map <leader>C :tabe ~/.vimrc<cr>
map <leader>CC :so ~/.vimrc<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"	2. Colors and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Set guicolors
set termguicolors

" Enable syntax highlighting
syntax enable 

" Enable 256 colors 
set t_Co=256

set background=dark

" Colorscheme
" let g:neosolarized_contrast = "high"
" let g:neosolarized_visibility = "high"
" colorscheme NeoSolarized
colorscheme dracula

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

autocmd CursorHold * silent call CocActionAsync('highlight')

" Always show the tab line
set stal=2

" lightline
let g:lightline = {
      \ 'colorscheme': 'dracula',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'cocstatus', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead',
      \   'cocstatus': 'coc#status'
      \ },
      \ }

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"	3. Tabs / Windows / Buffers
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Move between tabs
map [t gT
map ]t gt

" Useful mappings for managing tabs
nnoremap T <C-W>T
nmap <leader>tn :tabnew<cr>
nmap <leader>to :tabonly<cr>
nmap <leader>tc :tabclose<cr>

" toggle between this and the last accessed tab
let g:lasttab = 1
nmap <Leader><TAB> :exe "tabn ".g:lasttab<CR>

au TabLeave * let g:lasttab = tabpagenr()

nnoremap <leader>wt <C-W>T
nnoremap <leader>wo <C-W>o

" Switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"	4. Text formating
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set tabstop=2 softtabstop=2 expandtab shiftwidth=2 smarttab

" autocmd FileType python setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType scss setlocal iskeyword+=@-@

" Linebreak on 500 characters
set lbr
set tw=500

" Auto indent
set ai 
" Smart indent
set si 
" No wrap lines
set nowrap

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"	5. Editing mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" H to move to the first character in a line
noremap H ^
" L to move to the last character in a line
noremap L g_
