" Map space to leader
let maplocalleader = " "
let mapleader = " "

filetype on
set mouse=a number relativenumber hidden signcolumn=yes ignorecase history=500 updatetime=300 autoread clipboard+=unnamedplus nobackup nowb history=500 so=7 wildmenu cmdheight=1 hid smartcase hlsearch incsearch lazyredraw magic showmatch mat=2 noerrorbells novisualbell tm=500 foldcolumn=1 shortmess+=c t_vb= backspace=eol,start,indent switchbuf=useopen,usetab,newtab whichwrap+=<,>,h,l lbr tw=500 ai si nowrap

" Close 
nnoremap <leader>q :q<cr>

" Paste don't yank in normal
xnoremap p "_dP

" set tabs
set tabstop=2 softtabstop=2 expandtab shiftwidth=2 smarttab 
" autocmd FileType scss setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType scss setlocal iskeyword+=@-@

" Return to last edit position when opening files (You want this!)
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Disable highlight when <leader><cr> is pressed
map <silent> <C-l> :noh<cr>

" edit and load .vimrc
map <leader>C :tabe ~/.vimrc<cr>
map <leader>CC :so ~/.vimrc<cr>

" Set guicolors
set termguicolors

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Always show the tab line
set stal=1

nmap <C-n> :Vexplore<cr>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Move between tabs
map [t gT
map ]t gt

" Useful mappings for managing tabs
nnoremap T <C-W>T
nmap <leader>tn :tabnew<cr>
nmap <leader>to :tabonly<cr>
nmap <leader>tc :tabclose<cr>

nnoremap <leader>wt <C-W>T
nnoremap <leader>wo <C-W>o

" Switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>

" H to move to the first character in a line
noremap H ^
" L to move to the last character in a line
noremap L g_

