export ZSH="/home/xmichalx/.oh-my-zsh"
ZSH_THEME="jaischeema"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git git-flow pip python node npm)
source $ZSH/oh-my-zsh.sh

export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:/snap/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export MANPATH="/usr/local/man:$MANPATH"

function todo() {
  vim $HOME/Dokumenty/todo/$1
}

# Aliases
alias pip="pip3"
alias python="python3"
alias vim="nvim" 
alias q="exit" 
alias :q="exit"

alias youtube-wav="youtube-dl -x --audio-format wav"

# kitty
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"
export KITTY_CONFIG_DIRECTORY="$HOME/.config/kitty"
autoload -Uz compinit
compinit
kitty + complete setup zsh | source /dev/stdin
