export ZSH="/home/xmichalx/.oh-my-zsh"
ZSH_THEME="jaischeema"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git git-flow pip python node npm)
source $ZSH/oh-my-zsh.sh

# Aliases
alias pip="pip3"
alias python="python3"
alias vim="nvim" 
alias q="exit" 
alias :q="exit"

alias youtube-wav="youtube-dl -x --audio-format wav"

# kitty
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"
export KITTY_CONFIG_DIRECTORY="$HOME/.config/kitty"
autoload -Uz compinit
compinit
kitty + complete setup zsh | source /dev/stdin

function todo() {
  vim $HOME/Dokumenty/todo/$1
}

