export ZSH="/home/xmichalx/.oh-my-zsh"
ZSH_THEME="jaischeema"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git git-flow pip python node npm)
source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"

# Aliases
alias q="exit" 
alias :q="exit"

alias pip="pip3"
alias python="python3"

alias nv="nvim"
alias ff="ranger"
alias cat="batcat"

alias gs="git status"
alias ga="git add ."
alias gaa="git add"
alias gd="git diff"
alias gc="git commit"
alias gp="git push"

alias ek="$EDITOR $HOME/.config/kitty/kitty.conf"
alias ea="$EDITOR $HOME/.config/awesome/rc.lua"
alias en="$EDITOR $HOME/.config/nvim/init.lua"

alias youtube-wav="youtube-dl -x --audio-format wav"

# kitty
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"
export KITTY_CONFIG_DIRECTORY="$HOME/.config/kitty"
kitty + complete setup zsh | source /dev/stdin

function todo() {
  $EDITOR $HOME/Dokumenty/todo/$1
}

autoload -Uz compinit
compinit
